service: cat-bot

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  post-twitter:
    handler: src/index.handler
    events:
      - eventBridge:
          schedule: rate(1 minute)
    environment:
      TEST_ENV: "i am a test env var33"

# The "Resources" your "Functions" use. Raw AWS CloudFormation goes in here.
resources:
  Resources:
    CatBotS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:S3_BUCKET_NAME}
